apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: neodash
  app.kubernetes.io/name: neodash
  app.kubernetes.io/part-of: neodash

namespace: neodash
